# -*- coding: utf-8 -*-
"""
test_extract
========

Test extraction of Chemical Schematic Images

"""

import unittest
import os
import chemschematicresolver as csr
from skimage.transform import rescale
import copy

tests_dir = os.path.dirname(os.path.abspath(__file__))
train_dir = os.path.join(os.path.dirname(tests_dir), 'train')
train_markush_small_dir = os.path.join(train_dir, 'train_markush_small')
r_group_diag_dir = os.path.join(train_dir, 'r_group_diags')
train_imgs_dir = os.path.join(train_dir, 'train_imgs')


class TestExtract(unittest.TestCase):
    """ Tests the overall extraction case"""

    def do_extract_small(self, filename, gold):
        """ Extract images from the small markush directory"""

        path = os.path.join(train_markush_small_dir, filename)
        result = csr.extract.extract_diagram(path, debug=True)
        self.assertEqual(gold, result)

        return result

    def do_extract_all_imgs(self, dir_name=train_imgs_dir):
        """ Run extraction on the 'train_imgs' directory (no assertions)"""

        test_path = train_imgs_dir
        test_imgs = os.listdir(test_path)
        for img_path in test_imgs:
            full_path = os.path.join(test_path, img_path)
            csr.extract.extract_diagram(full_path, debug=True)

    def test_run_train_imgs(self):
        """ Run all images in train_imgs directory"""
        self.do_extract_all_imgs()

    def test_r_group_extract(self):

        gold = [(['EtNAPH'], 'c1c2n(c3c(c2ccc1)cc(cc3)/C=C/c1ccc(/C=C/c2ccc3n(c4ccccc4c3c2)CC)c2c1cccc2)CC'),
                (['MeNAPH'], 'c1c(ccc(c1)N(c1ccc(/C=C/c2c3c(c(cc2)/C=C/c2ccc(N(c4ccc(C)cc4)c4ccc(cc4)C)cc2)cccc3)cc1)c1ccc(C)cc1)C'),
                (['MeONAPH'], 'c1c(ccc(c1)N(c1ccc(/C=C/c2c3c(c(cc2)/C=C/c2ccc(N(c4ccc(OC)cc4)c4ccc(cc4)OC)cc2)cccc3)cc1)c1ccc(OC)cc1)OC')]

        self.do_extract_small('S014372081630119X_gr1.jpg', gold)

    def test_r_group_extract2(self):

        # This example fails as the chemical names need to be resolved

        gold = []

        self.do_extract_small('S0143720816300286_gr1.jpg', gold)

    def test_r_group_extract3(self):

        # NB : This test is automatically filtering out the failed R-group resolution from the presence of wildcards

        gold = [(['107'], 'c1c2ccc3cccc4c3c2c(cc4)cc1/C=N/CCSSCC/N=C/c1cc2ccc3cccc4ccc(c1)c2c34'),
                (['106'], 'c1c2ccc3cc(/C=N/c4ccccc4O)c(O)c4c3c2c(cc1)cc4')]

        self.do_extract_small('S0143720816301115_r75.jpg', gold)

    def test_r_group_extract4(self):

        # Identified one of the numeric labels as an atom indicator (inside osra)
        # Could be solved by doing a numerical clean

        gold = [(['1'], 'N(CC)(CC)c1ccc2cc(C#N)c(=N)oc2c1'),
                (['2'], 'N(CC)(CC)c1ccc2cc(C#N)/c(=N/C(=O)OCC)/oc2c1'),
                (['3'], 'N(CC)(CC)c1ccc2cc(C#N)c(=O)oc2c1'),
                (['4'], 'N(CC)(CC)c1ccc2ccc(=O)oc2c1')]

        self.do_extract_small('S0143720816301681_gr1.jpg', gold)

    def do_extract_r_group_diags(self, filename, gold):
        """ Extract images from the small markush directory"""

        path = os.path.join(r_group_diag_dir, filename)
        result = csr.extract.extract_diagram(path, debug=True)
        self.assertEqual(gold, result)

    def test_r_group_diag_1(self):

        # Identified numerical points as labels

        gold = []

        self.do_extract_r_group_diags('S0143720816301565_gr1.jpg', gold)

    def test_r_group_diag_2(self):

        # Octyl and Hectyl resolved correctly. NB the smiles are still wrong though due to OSRA failing
        # Need to improve the relative label-detection as well : at the moment it's just returning all candidates

        gold = [(['A'],
                'c1(ccc(s1)c1cc(F)c(c2cc3S4(c5c(c3s2)sc(c5)c2c([F]CC(C4)CCCC)cc(c3sc(c4ccc(CCCCCC)s4)cc3)c3nsnc23)CC(CC)CCCC)c2nsnc12)c1sc(CCCCCC)cc1'),
                (['1'],
                'N1(C(=O)c2c(C1=O)ccc(c1sc(c3cc(F)c(c4cc5S6(c7c(c5s4)sc(c7)c4c([F]CC(C6)CCCC)cc(c5sc(cc5)c5ccc6C(=O)N(C(=O)c6c5)CCCCCCCC)c5nsnc45)CC(CC)CCCC)c4nsnc34)cc1)c2)CCCCCCCC'),
                (['2'],
                'N1(C(=O)c2c(C1=O)ccc(c1sc(c3cc(F)c(c4cc5S6(c7c(c5s4)sc(c7)c4c([F]CC(C6)CCCC)cc(c5sc(cc5)c5ccc6C(=O)N(C(=O)c6c5)CCCCCC)c5nsnc45)CC(CC)CCCC)c4nsnc34)cc1)c2)CCCCCC')]

        self.do_extract_r_group_diags('S0143720816302054_sc1.jpg', gold)

    def test_r_group_diag_3(self):

        # Has assigned the same label to both diagrams, resulting in different outcomes
        # Either some of the 4 R-values are not resolved, or something else is going wrong on the rgroup diag

        gold = []

        self.do_extract_r_group_diags('S0143720816302108_gr1.jpg', gold)

    def test_r_group_diag_4(self):

        # Schematic flow diagram, including arrows etc

        gold = []

        self.do_extract_r_group_diags('S0143720816301826_sc1.jpg', gold)


    def test_r_group_diag_5(self):

        # Containing segmenting lines, and large R-groups

        gold = []

        self.do_extract_r_group_diags('S0143720816301401_gr5.jpg', gold)

    def do_extract_train_imgs(self, filename, gold):
        """ Extract images from the train_imgs directory"""

        path = os.path.join(train_imgs_dir, filename)
        result = csr.extract.extract_diagram(path, debug=False)
        self.assertEqual(gold, result)

    def test_train_imgs_1(self):

        gold = []

        self.do_extract_train_imgs('S0143720816301115_gr1.jpg', gold)

    def test_extract_document(self):
        path = os.path.join(train_dir, 'train_docs', '10.1039_C4TC01753F.html')
        records = csr.extract.extract_document(path)
        import pprint
        pp = pprint.PrettyPrinter(indent=4)
        pp.pprint(records)

    def test_substitute_labels(self):
        records = [{'names': ['pyrenes']},
                    {'names': ['Godumala Mallesham']},
                    {'names': ['Cedex']},
                    {'names': ['diphenyl phosphine–oxide']},
                    {'names': ['diarylamino']},
                    {'names': ['anthracene']},
                    {'names': ['triphenylamine']},
                    {'names': ['diphenyl']},
                    {'names': ['phosphine']},
                    {'names': ['oxide']},
                    {'names': ['biphenyl']},
                    {'diag': ['csd']},
                    {'names': ['bromo pyrene 1']},
                    {'names': ['2,7-dibromo-9,9-dimethyl-9H-fluorene']},
                    {'names': ['aryl lithio']},
                    {'names': ['hydrogen peroxide']},
                    {'names': ['non-pyrene']},
                    {'names': ['amine']},
                    {'names': ['hydroxyl']},
                    {'names': ['C2–H2 ⋯ O1']},
                    {'diag': ['csd']},
                    {'names': ['calomel']},
                    {'names': ['ferrocenium']},
                    {'names': ['acetonitrile']},
                    {'names': ['methanol']},
                    {'names': ['diphenyl phospheneoxide']},
                    {'names': ['4,4′-bis[N-(1-naphthyl)-N-phenyl amino ] biphenyl']},
                    {'names': ['Cd']},
                    {'names': ['carbozole–dimesitylborane']},
                    {'names': ['triphenylamine–imidazole']},
                    {'names': ['Li']},
                    {'names': ['1 × 10 − 4 to 5 × 10 − 4 cm2 V−1 s−1']},
                    {'names': ['toluene']},
                    {'names': ['nitrogen gas']},
                    {'names': ['n-hexane']},
                    {'names': ['chloroform–hexane']},
                    {'names': ['dry methanol']},
                    {'names': ['sodium sulfate']},
                    {'names': ['H2O2']},
                    {'names': ['diethyl ether']},
                    {'names': ['C28H19OP']},
                    {'names': ['12H']},
                    {'names': ['C40H27OP']},
                    {'names': ['( hexane–ethylacetate 1 : 1 )']},
                    {'names': ['C43H31OP']},
                    {'names': ['phosphoric acid']},
                    {'names': ['CH']},
                    {'names': ['glassy carbon']},
                    {'names': ['Ag']},
                    {'names': ['AgCl']},
                    {'names': ['platinum']},
                    {'names': ['alumina']},
                    {'names': ['Ti']},
                    {'names': ['sapphire']},
                    {'names': ['CH3OH–CHCl3']},
                    {'names': ['trichloroethylene']},
                    {'names': ['acetone']},
                    {'names': ['isopropyl alcohol']},
                    {'names': ['ozone']},
                    {'names': ['quartz']},
                    {'names': ['N,N-Diphenyl-N′,N′-bis(1-naphthyl)-1,1′-biphenyl-4,4′-diamine']},
                    {'names': ['2,9-dimethyl-4,7-diphenyl-1,10-phenanthroline', 'BCP']},
                    {'names': ['tris(8-hydroxyquinoline)-aluminium']},
                    {'names': ['Hyderabad 500007']},
                    {'names': ['C–H ⋯ O']},
                    {'names': ['fluorene']},
                    {'names': ['methyl']},
                    {'labels': ['3'], 'names': ['dibromo'], 'roles': ['derivative']},
                    {'labels': ['4'], 'roles': ['compound']},
                    {'names': ['1,4-dibromobenzene', '1,4-Dibromobenzene']},
                    {'names': ['4,4′-dibromobiphenyl']},
                    {'names': ['1,3-dibromobenzene']},
                    {'names': ['1,4-dibromo-2,5-dimethylbenzene']},
                    {'names': ['H']},
                    {'names': ['hydrogen']},
                    {'names': ['O']},
                    {'names': ['ferrocene']},
                    {'names': ['aryl']},
                    {'names': ['quinine sulphate']},
                    {'names': ['Na2SO4']},
                    {'names': ['dichloromethane']},
                    {'names': ['THF']},
                    {'names': ['C–H']},
                    {'names': ['phenyl']},
                    {'names': ['diphenyl phosphine oxide', 'diphenylphosphine oxide']},
                    {'names': ['TCNQ', '2,3,5,6-tetrafluoro-7,7′,8,8′-tetracyanoquinodimethane']},
                    {'labels': ['6'],
                    'melting_points': [{'units': '°C', 'value': '217–220'}],
                    'names': ['1-(4′-bromobiphenyl-4-yl)pyrene'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'multiplicity': 'm',
                                              'number': '4H',
                                              'shift': '8.28–8.16'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '8.13–8.10'},
                                             {'multiplicity': 'm',
                                              'number': '3H',
                                              'shift': '8.08–8.00'},
                                             {'multiplicity': 'm',
                                              'number': '4H',
                                              'shift': '7.79–7.69'},
                                             {'multiplicity': 'm',
                                              'number': '4H',
                                              'shift': '7.66–7.57'}],
                                   'solvent': 'CDCl3'}],
                    'roles': ['product', 'compound']},
                    {'names': ['Pd(PPh3)4']},
                    {'names': ['K2CO3']},
                    {'labels': ['7'],
                    'melting_points': [{'units': '°C', 'value': '125–127'}],
                    'names': ['1-(3-bromophenyl)pyrene'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '8.21'},
                                             {'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.17'},
                                             {'multiplicity': 'm',
                                              'number': '3H',
                                              'shift': '8.13–8.07'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '8.06–8.00'},
                                             {'coupling': '7.9',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.93'},
                                             {'coupling': '1.5',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 't',
                                              'number': '1H',
                                              'shift': '7.79'},
                                             {'coupling': '8.1',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.60'},
                                             {'coupling': '7.6',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.55'},
                                             {'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 't',
                                              'number': '1H',
                                              'shift': '7.42'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '143.26'},
                                             {'shift': '135.85'},
                                             {'shift': '133.33'},
                                             {'shift': '131.35'},
                                             {'shift': '130.85'},
                                             {'shift': '130.81'},
                                             {'shift': '130.23'},
                                             {'shift': '129.80'},
                                             {'shift': '129.21'},
                                             {'shift': '128.33'},
                                             {'shift': '127.80'},
                                             {'shift': '127.64'},
                                             {'shift': '127.38'},
                                             {'shift': '127.27'},
                                             {'shift': '126.05'},
                                             {'shift': '125.28'},
                                             {'shift': '124.99'},
                                             {'shift': '124.82'},
                                             {'shift': '124.72'},
                                             {'shift': '124.67'},
                                             {'shift': '124.57'},
                                             {'shift': '122.44'}],
                                   'solvent': 'CDCl3'}],
                    'roles': ['product', 'compound']},
                    {'labels': ['8'],
                    'melting_points': [{'units': '°C', 'value': '119–121'}],
                    'names': ['1-(4-bromo-2,5-dimethylphenyl)pyrene'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '7.9',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '8.17'},
                                             {'multiplicity': 'm',
                                              'number': '1H',
                                              'shift': '8.16–8.11'},
                                             {'multiplicity': 's',
                                              'number': '2H',
                                              'shift': '8.07'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '8.01–7.93'},
                                             {'coupling': '7.7',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.80'},
                                             {'coupling': '9.1',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.68'},
                                             {'multiplicity': 's',
                                              'number': '1H',
                                              'shift': '7.56'},
                                             {'multiplicity': 's',
                                              'number': '1H',
                                              'shift': '7.21'},
                                             {'multiplicity': 's',
                                              'number': '3H',
                                              'shift': '2.43'},
                                             {'multiplicity': 's',
                                              'number': '3H',
                                              'shift': '1.96'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '139.86'},
                                             {'shift': '136.36'},
                                             {'shift': '136.04'},
                                             {'shift': '134.88'},
                                             {'shift': '133.38'},
                                             {'shift': '132.87'},
                                             {'shift': '131.33'},
                                             {'shift': '130.89'},
                                             {'shift': '130.62'},
                                             {'shift': '128.77'},
                                             {'shift': '127.60'},
                                             {'shift': '127.38'},
                                             {'shift': '127.35'},
                                             {'shift': '127.09'},
                                             {'shift': '126.02'},
                                             {'shift': '125.17'},
                                             {'shift': '125.08'},
                                             {'shift': '124.99'},
                                             {'shift': '124.73'},
                                             {'shift': '124.66'},
                                             {'shift': '124.50'},
                                             {'shift': '123.91'},
                                             {'shift': '22.38'},
                                             {'shift': '19.47'}],
                                   'solvent': 'CDCl3'}],
                    'roles': ['product', 'compound']},
                    {'labels': ['2'], 'names': ['borolane'], 'roles': ['compound', 'derivative']},
                    {'labels': ['9'],
                    'melting_points': [{'units': '°C', 'value': '186–188'}],
                    'names': ['1-(7-bromo-9,9-dimethyl-9H-fluoren-2-yl)pyrene'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '2.0',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.25'},
                                             {'coupling': '3.4',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.24'},
                                             {'coupling': '7.6 , 1.1',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'dd',
                                              'number': '1H',
                                              'shift': '8.21'},
                                             {'coupling': '7.6',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.17'},
                                             {'coupling': '0.6',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '8.11'},
                                             {'multiplicity': 'm',
                                              'number': '3H',
                                              'shift': '8.06–8.01'},
                                             {'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.86'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '7.70–7.66'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '7.64–7.61'},
                                             {'coupling': '8.1 , 1.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'dd',
                                              'number': '1H',
                                              'shift': '7.52'},
                                             {'multiplicity': 's',
                                              'number': '6H',
                                              'shift': '1.57'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '155.89'},
                                             {'shift': '153.43'},
                                             {'shift': '140.63'},
                                             {'shift': '137.90'},
                                             {'shift': '137.82'},
                                             {'shift': '137.20'},
                                             {'shift': '131.43'},
                                             {'shift': '130.89'},
                                             {'shift': '130.54'},
                                             {'shift': '130.19'},
                                             {'shift': '129.74'},
                                             {'shift': '128.46'},
                                             {'shift': '127.60'},
                                             {'shift': '127.51'},
                                             {'shift': '127.38'},
                                             {'shift': '126.19'},
                                             {'shift': '125.99'},
                                             {'shift': '125.16'},
                                             {'shift': '125.12'},
                                             {'shift': '124.88'},
                                             {'shift': '124.79'},
                                             {'shift': '124.63'},
                                             {'shift': '121.47'},
                                             {'shift': '121.13'},
                                             {'shift': '119.88'},
                                             {'shift': '47.23'},
                                             {'shift': '27.04'}],
                                   'solvent': 'CDCl3'}],
                    'roles': ['product', 'compound']},
                    {'names': ['chloroform']},
                    {'names': ['chloroform–diethyl ether']},
                    {'names': ['cyclohexane']},
                    {'names': ['ethyl acetate']},
                    {'names': ['n-BuLi']},
                    {'names': ['chlorodiphenylphosphine']},
                    {'names': ['31P']},
                    {'names': ['nitrogen']},
                    {'names': ['LiF']},
                    {'names': ['Al']},
                    {'names': ['Phosphine oxide', 'phosphine oxide']},
                    {'names': ['ITO',
                            'indium tin oxide',
                            'indium – tin oxide',
                            'indium–tin oxide']},
                    {'names': ['CHCl3']},
                    {'names': ['α-NPD']},
                    {'labels': ['5', '1'],
                    'melting_points': [{'units': '°C', 'value': '142–144'}],
                    'names': ['1-(4-bromophenyl)pyrene', 'mono bromo', 'bromo'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '7.9',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '8.18'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '8.16–8.09'},
                                             {'multiplicity': 's',
                                              'number': '2H',
                                              'shift': '8.07'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '8.03–7.96'},
                                             {'coupling': '7.9',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.90'},
                                             {'coupling': '8.3',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '7.67'},
                                             {'coupling': '8.3',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '7.47'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '144.87'},
                                             {'shift': '136.05'},
                                             {'shift': '133.09'},
                                             {'shift': '132.13'},
                                             {'shift': '131.99'},
                                             {'shift': '131.92'},
                                             {'shift': '131.26'},
                                             {'shift': '130.88'},
                                             {'shift': '130.71'},
                                             {'shift': '130.53'},
                                             {'shift': '128.58'},
                                             {'shift': '128.44'},
                                             {'shift': '128.21'},
                                             {'shift': '127.80'},
                                             {'shift': '127.68'},
                                             {'shift': '127.25'},
                                             {'shift': '127.18'},
                                             {'shift': '126.04'},
                                             {'shift': '125.26'},
                                             {'shift': '124.97'},
                                             {'shift': '124.77'},
                                             {'shift': '124.57'}],
                                   'solvent': 'CDCl3'}],
                    'roles': ['product', 'compound', 'intermediates']},
                    {'names': ['hexane']},
                    {'names': ['2H']},
                    {'ir_spectra': [{'peaks': [{'units': 'cm−1', 'value': '3041'},
                                            {'units': 'cm−1', 'value': '1589'},
                                            {'units': 'cm−1', 'value': '1197'},
                                            {'units': 'cm−1', 'value': '831'},
                                            {'units': 'cm−1', 'value': '692'}],
                                  'solvent': 'KBr'}],
                    'labels': ['11'],
                    'melting_points': [{'units': '°C', 'value': '208'}],
                    'names': ['diphenyl(4-(pyren-1-yl)phenyl)phosphine oxide'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '144.98'},
                                             {'shift': '144.95'},
                                             {'shift': '136.13'},
                                             {'shift': '133.20'},
                                             {'shift': '132.17'},
                                             {'shift': '132.04'},
                                             {'shift': '131.98'},
                                             {'shift': '131.82'},
                                             {'shift': '131.34'},
                                             {'shift': '130.94'},
                                             {'shift': '130.78'},
                                             {'shift': '130.73'},
                                             {'shift': '130.57'},
                                             {'shift': '128.62'},
                                             {'shift': '128.46'},
                                             {'shift': '128.28'},
                                             {'shift': '127.83'},
                                             {'shift': '127.72'},
                                             {'shift': '127.28'},
                                             {'shift': '127.24'},
                                             {'shift': '126.07'},
                                             {'shift': '125.32'},
                                             {'shift': '125.00'},
                                             {'shift': '124.85'},
                                             {'shift': '124.70'},
                                             {'shift': '124.62'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '500',
                                   'frequency_units': 'MHz',
                                   'nucleus': '31P',
                                   'peaks': [{'shift': '29.141'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 't',
                                              'number': '2H',
                                              'shift': '8.19'},
                                             {'coupling': '7.5',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.15'},
                                             {'coupling': '9.2',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.11'},
                                             {'coupling': '1.4',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '8.07'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '8.03–7.98'},
                                             {'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.93'},
                                             {'multiplicity': 'm',
                                              'number': '6H',
                                              'shift': '7.88–7.78'},
                                             {'coupling': '8.1 , 2.4',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'dd',
                                              'number': '2H',
                                              'shift': '7.72'},
                                             {'multiplicity': 'm',
                                              'number': '6H',
                                              'shift': '7.60–7.50'}],
                                   'solvent': 'CDCl3'}],
                    'quantum_yields': [{'type': 'Φf', 'value': '0.67'}],
                    'roles': ['product', 'compound'],
                    'uvvis_spectra': [{'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '270'},
                                               {'units': 'nm', 'value': '281'},
                                               {'units': 'nm', 'value': '330'},
                                               {'units': 'nm', 'value': '346'},
                                               {'units': 'nm', 'value': '355'}],
                                     'solvent': 'chloroform'},
                                    {'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '480'}],
                                     'solvent': 'chloroform'}]},
                    {'ir_spectra': [{'peaks': [{'units': 'cm−1', 'value': '3047'},
                                            {'units': 'cm−1', 'value': '1594'},
                                            {'units': 'cm−1', 'value': '1180'},
                                            {'units': 'cm−1', 'value': '849'},
                                            {'units': 'cm−1', 'value': '696'}],
                                  'solvent': 'KBr'}],
                    'labels': ['12'],
                    'melting_points': [{'units': '°C', 'value': '244'}],
                    'names': ['diphenyl(4′-(pyren-1-yl)-[1,1′-biphenyl]-4-yl)phosphine oxide'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '144.24'},
                                             {'shift': '141.11'},
                                             {'shift': '138.64'},
                                             {'shift': '136.85'},
                                             {'shift': '133.21'},
                                             {'shift': '132.74'},
                                             {'shift': '132.60'},
                                             {'shift': '132.15'},
                                             {'shift': '132.01'},
                                             {'shift': '131.41'},
                                             {'shift': '131.15'},
                                             {'shift': '130.88'},
                                             {'shift': '130.69'},
                                             {'shift': '130.50'},
                                             {'shift': '128.61'},
                                             {'shift': '128.45'},
                                             {'shift': '127.59'},
                                             {'shift': '127.51'},
                                             {'shift': '127.47'},
                                             {'shift': '127.34'},
                                             {'shift': '127.19'},
                                             {'shift': '127.03'},
                                             {'shift': '126.03'},
                                             {'shift': '125.18'},
                                             {'shift': '125.03'},
                                             {'shift': '124.87'},
                                             {'shift': '124.66'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '500',
                                   'frequency_units': 'MHz',
                                   'nucleus': '31P',
                                   'peaks': [{'shift': '28.996'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'multiplicity': 'm',
                                              'number': '4H',
                                              'shift': '8.24–8.15'},
                                             {'multiplicity': 's',
                                              'number': '2H',
                                              'shift': '8.09'},
                                             {'multiplicity': 'm',
                                              'number': '3H',
                                              'shift': '8.05–7.98'},
                                             {'multiplicity': 'm',
                                              'number': '12H',
                                              'shift': '7.81–7.70'},
                                             {'multiplicity': 'm',
                                              'number': '6H',
                                              'shift': '7.60–7.47'}],
                                   'solvent': 'CDCl3'}],
                    'quantum_yields': [{'type': 'Φf', 'value': '0.87'}],
                    'roles': ['product', 'compound'],
                    'uvvis_spectra': [{'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '269'},
                                               {'units': 'nm', 'value': '281'},
                                               {'units': 'nm', 'value': '330'},
                                               {'units': 'nm', 'value': '347'},
                                               {'units': 'nm', 'value': '362'}],
                                     'solvent': 'chloroform'},
                                    {'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '476'}],
                                     'solvent': 'chloroform'}]},
                    {'names': ['13C']},
                    {'names': ['1H']},
                    {'ir_spectra': [{'peaks': [{'units': 'cm−1', 'value': '3048'},
                                            {'units': 'cm−1', 'value': '2917'},
                                            {'units': 'cm−1', 'value': '1598'},
                                            {'units': 'cm−1', 'value': '1186'},
                                            {'units': 'cm−1', 'value': '848'},
                                            {'units': 'cm−1', 'value': '717'}],
                                  'solvent': 'KBr'}],
                    'labels': ['14'],
                    'melting_points': [{'units': '°C', 'value': '188'}],
                    'names': ['(2,5-dimethyl-4-(pyren-1-yl)phenyl)diphenyl phosphine oxide'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '7.9',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 't',
                                              'number': '2H',
                                              'shift': '8.21'},
                                             {'coupling': '7.2',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.17'},
                                             {'multiplicity': 's',
                                              'number': '2H',
                                              'shift': '8.10'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '8.03–7.99'},
                                             {'coupling': '7.9',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.84'},
                                             {'multiplicity': 'm',
                                              'number': '4H',
                                              'shift': '7.83–7.77'},
                                             {'coupling': '9.1',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.67'},
                                             {'multiplicity': 'm',
                                              'number': '6H',
                                              'shift': '7.61–7.50'},
                                             {'coupling': '4.3',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.31'},
                                             {'coupling': '14.3',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.09'},
                                             {'multiplicity': 's',
                                              'number': '3H',
                                              'shift': '2.47'},
                                             {'multiplicity': 's',
                                              'number': '3H',
                                              'shift': '1.90'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '144.58'},
                                             {'shift': '140.10'},
                                             {'shift': '139.99'},
                                             {'shift': '135.91'},
                                             {'shift': '135.07'},
                                             {'shift': '134.92'},
                                             {'shift': '134.28'},
                                             {'shift': '134.14'},
                                             {'shift': '133.96'},
                                             {'shift': '133.79'},
                                             {'shift': '133.56'},
                                             {'shift': '132.19'},
                                             {'shift': '132.04'},
                                             {'shift': '131.93'},
                                             {'shift': '131.78'},
                                             {'shift': '131.26'},
                                             {'shift': '130.82'},
                                             {'shift': '130.68'},
                                             {'shift': '128.64'},
                                             {'shift': '128.47'},
                                             {'shift': '127.68'},
                                             {'shift': '127.45'},
                                             {'shift': '127.27'},
                                             {'shift': '126.69'},
                                             {'shift': '126.02'},
                                             {'shift': '125.21'},
                                             {'shift': '125.03'},
                                             {'shift': '124.92'},
                                             {'shift': '124.45'},
                                             {'shift': '21.23'},
                                             {'shift': '19.75'}],
                                   'solvent': 'CDCl3'}],
                    'quantum_yields': [{'type': 'Φf', 'value': '0.51'}],
                    'roles': ['product', 'compound', 'compounds', 'data of'],
                    'uvvis_spectra': [{'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '269'},
                                               {'units': 'nm', 'value': '279'},
                                               {'units': 'nm', 'value': '315'},
                                               {'units': 'nm', 'value': '330'},
                                               {'units': 'nm', 'value': '345'},
                                               {'units': 'nm', 'value': '341'}],
                                     'solvent': 'chloroform'},
                                    {'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '465'}],
                                     'solvent': 'chloroform'}]},
                    {'names': ['CDCl3']},
                    {'ir_spectra': [{'peaks': [{'units': 'cm−1', 'value': '3038'},
                                            {'units': 'cm−1', 'value': '2961'},
                                            {'units': 'cm−1', 'value': '1598'},
                                            {'units': 'cm−1', 'value': '1434'},
                                            {'units': 'cm−1', 'value': '1192'},
                                            {'units': 'cm−1', 'value': '844'},
                                            {'units': 'cm−1', 'value': '696'}],
                                  'solvent': 'KBr'}],
                    'labels': ['15'],
                    'melting_points': [{'units': '°C', 'value': '273'}],
                    'names': ['(9,9-dimethyl-7-(pyren-1-yl)-9H-fluoren-2-yl)diphenylphosphine '
                            'oxide'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '500',
                                   'frequency_units': 'MHz',
                                   'nucleus': '31P',
                                   'peaks': [{'shift': '29.932'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '9.1',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '8.22'},
                                             {'coupling': '7.6',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.18'},
                                             {'coupling': '7.6',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.15'},
                                             {'multiplicity': 's',
                                              'number': '2H',
                                              'shift': '8.08'},
                                             {'multiplicity': 'm',
                                              'number': '4H',
                                              'shift': '8.05–7.97'},
                                             {'coupling': '7.6',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.90'},
                                             {'coupling': '7.8 , 2.3',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'dd',
                                              'number': '1H',
                                              'shift': '7.82'},
                                             {'multiplicity': 'm',
                                              'number': '5H',
                                              'shift': '7.78–7.70'},
                                             {'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '7.62'},
                                             {'multiplicity': 'm',
                                              'number': '7H',
                                              'shift': '7.58–7.46'},
                                             {'multiplicity': 's',
                                              'number': '6H',
                                              'shift': '1.56'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '154.52'},
                                             {'shift': '154.10'},
                                             {'shift': '153.94'},
                                             {'shift': '142.69'},
                                             {'shift': '141.48'},
                                             {'shift': '137.59'},
                                             {'shift': '136.87'},
                                             {'shift': '133.51'},
                                             {'shift': '132.10'},
                                             {'shift': '131.97'},
                                             {'shift': '131.84'},
                                             {'shift': '131.35'},
                                             {'shift': '131.27'},
                                             {'shift': '131.19'},
                                             {'shift': '130.81'},
                                             {'shift': '130.54'},
                                             {'shift': '129.88'},
                                             {'shift': '129.74'},
                                             {'shift': '128.50'},
                                             {'shift': '128.35'},
                                             {'shift': '127.52'},
                                             {'shift': '127.39'},
                                             {'shift': '127.30'},
                                             {'shift': '126.46'},
                                             {'shift': '126.34'},
                                             {'shift': '125.95'},
                                             {'shift': '125.09'},
                                             {'shift': '125.01'},
                                             {'shift': '124.97'},
                                             {'shift': '124.77'},
                                             {'shift': '124.58'},
                                             {'shift': '120.54'},
                                             {'shift': '119.86'},
                                             {'shift': '119.68'},
                                             {'shift': '47.28'},
                                             {'shift': '26.90'}],
                                   'solvent': 'CDCl3'}],
                    'quantum_yields': [{'type': 'Φf', 'value': '0.88'}],
                    'roles': ['product', 'compound'],
                    'uvvis_spectra': [{'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '268'},
                                               {'units': 'nm', 'value': '280'},
                                               {'units': 'nm', 'value': '312'},
                                               {'units': 'nm', 'value': '351'},
                                               {'units': 'nm', 'value': '368'}],
                                     'solvent': 'chloroform'},
                                    {'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '473'}],
                                     'solvent': 'chloroform'}]},
                    {'ir_spectra': [{'peaks': [{'units': 'cm−1', 'value': '3049'},
                                            {'units': 'cm−1', 'value': '1585'},
                                            {'units': 'cm−1', 'value': '1187'},
                                            {'units': 'cm−1', 'value': '847'},
                                            {'units': 'cm−1', 'value': '695'}],
                                  'solvent': 'KBr'}],
                    'labels': ['10'],
                    'melting_points': [{'units': '°C', 'value': '243'}],
                    'names': ['diphenyl(pyren-1-yl)phosphine oxide'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '9.1',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.93'},
                                             {'multiplicity': 'm',
                                              'number': '3H',
                                              'shift': '8.27–8.15'},
                                             {'multiplicity': 'm',
                                              'number': '4H',
                                              'shift': '8.11–8.00'},
                                             {'multiplicity': 'm',
                                              'number': '5H',
                                              'shift': '7.80–7.67'},
                                             {'multiplicity': 'm',
                                              'number': '2H',
                                              'shift': '7.60–7.52'},
                                             {'multiplicity': 'm',
                                              'number': '4H',
                                              'shift': '7.51–7.42'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '134.16'},
                                             {'shift': '133.89'},
                                             {'shift': '132.50'},
                                             {'shift': '132.22'},
                                             {'shift': '132.09'},
                                             {'shift': '131.85'},
                                             {'shift': '131.22'},
                                             {'shift': '131.06'},
                                             {'shift': '130.94'},
                                             {'shift': '130.34'},
                                             {'shift': '129.82'},
                                             {'shift': '128.87'},
                                             {'shift': '128.66'},
                                             {'shift': '128.50'},
                                             {'shift': '127.06'},
                                             {'shift': '126.44'},
                                             {'shift': '126.28'},
                                             {'shift': '126.15'},
                                             {'shift': '123.59'},
                                             {'shift': '123.41'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '500',
                                   'frequency_units': 'MHz',
                                   'nucleus': '31P',
                                   'peaks': [{'shift': '32.886'}],
                                   'solvent': 'CDCl3'}],
                    'quantum_yields': [{'type': 'Φf', 'value': '0.91'}],
                    'roles': ['data of',
                            'product',
                            'compound',
                            'compounds',
                            'data for',
                            'derivatives'],
                    'uvvis_spectra': [{'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '491'}],
                                     'solvent': 'chloroform'},
                                    {'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '271'},
                                               {'units': 'nm', 'value': '282'},
                                               {'units': 'nm', 'value': '325'},
                                               {'units': 'nm', 'value': '339'},
                                               {'units': 'nm', 'value': '353'},
                                               {'units': 'nm', 'value': '350'}],
                                     'solvent': 'chloroform'}]},
                    {'ir_spectra': [{'peaks': [{'units': 'cm−1', 'value': '3039'},
                                            {'units': 'cm−1', 'value': '1582'},
                                            {'units': 'cm−1', 'value': '1187'},
                                            {'units': 'cm−1', 'value': '851'},
                                            {'units': 'cm−1', 'value': '697'}],
                                  'solvent': 'KBr'}],
                    'labels': ['13'],
                    'melting_points': [{'units': '°C', 'value': '196'}],
                    'names': ['pyrene',
                            'Pyrene',
                            'diphenyl(3-(pyren-1-yl)phenyl)phosphine oxide'],
                    'nmr_spectra': [{'apparatus': 'Bruker Avance',
                                   'frequency': '300',
                                   'frequency_units': 'MHz',
                                   'nucleus': '1H',
                                   'peaks': [{'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '8.17'},
                                             {'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '1H',
                                              'shift': '8.14'},
                                             {'coupling': '2.9',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '8.05'},
                                             {'multiplicity': 'm',
                                              'number': '3H',
                                              'shift': '8.03–7.93'},
                                             {'coupling': '7.8',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'd',
                                              'number': '2H',
                                              'shift': '7.91'},
                                             {'multiplicity': 'm',
                                              'number': '6H',
                                              'shift': '7.86–7.75'},
                                             {'coupling': '7.6 , 2.9',
                                              'coupling_units': 'Hz',
                                              'multiplicity': 'td',
                                              'number': '1H',
                                              'shift': '7.66'},
                                             {'multiplicity': 'm',
                                              'number': '6H',
                                              'shift': '7.56–7.45'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '75',
                                   'frequency_units': 'MHz',
                                   'nucleus': '13C',
                                   'peaks': [{'shift': '141.45'},
                                             {'shift': '141.36'},
                                             {'shift': '136.08'},
                                             {'shift': '134.07'},
                                             {'shift': '134.05'},
                                             {'shift': '133.92'},
                                             {'shift': '133.84'},
                                             {'shift': '133.37'},
                                             {'shift': '132.80'},
                                             {'shift': '132.55'},
                                             {'shift': '132.09'},
                                             {'shift': '132.01'},
                                             {'shift': '131.97'},
                                             {'shift': '131.95'},
                                             {'shift': '131.31'},
                                             {'shift': '130.93'},
                                             {'shift': '130.85'},
                                             {'shift': '130.80'},
                                             {'shift': '130.73'},
                                             {'shift': '128.61'},
                                             {'shift': '128.56'},
                                             {'shift': '128.52'},
                                             {'shift': '128.46'},
                                             {'shift': '128.25'},
                                             {'shift': '127.73'},
                                             {'shift': '127.62'},
                                             {'shift': '127.47'},
                                             {'shift': '127.23'},
                                             {'shift': '126.02'},
                                             {'shift': '125.25'},
                                             {'shift': '124.91'},
                                             {'shift': '124.79'},
                                             {'shift': '124.67'},
                                             {'shift': '124.59'},
                                             {'shift': '124.51'}],
                                   'solvent': 'CDCl3'},
                                  {'apparatus': 'Bruker Avance',
                                   'frequency': '500',
                                   'frequency_units': 'MHz',
                                   'nucleus': '31P',
                                   'peaks': [{'shift': '29.01'}],
                                   'solvent': 'CDCl3'}],
                    'quantum_yields': [{'type': 'Φf', 'value': '0.54'}],
                    'roles': ['product', 'compound', 'data for', 'data of', 'derivative'],
                    'uvvis_spectra': [{'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '272'},
                                               {'units': 'nm', 'value': '281'},
                                               {'units': 'nm', 'value': '330'},
                                               {'units': 'nm', 'value': '348'},
                                               {'units': 'nm', 'value': '354'}],
                                     'solvent': 'chloroform'},
                                    {'apparatus': 'Jasco V-550 spectrophotometer',
                                     'peaks': [{'units': 'nm', 'value': '467'}],
                                     'solvent': 'chloroform'}]}]

        results = [   [   (   ['12'],
                            'c12cccc3ccc4c(ccc(cc1)c4c23)c1ccc(C2=CC=C(CC2)P(=O)(C2=CCCC=C2)C2CCCCC2)cc1'),
                        (   ['15'],
                            'c1c2ccc3ccc(c4ccc5C6=C(C=C(CC6)[C](=O)(C6=CCCC=C6)C6C=CC=CC6)C(C)(C)c5c4)c4ccc(cc1)c2c34'),
                        (   ['11'],
                            'c1c2ccc3CCC(=c4ccc(cc1)c2c34)c1ccc(P(C2CCCCC2)(O)C2C=CC=CC2)cc1'),
                        (['u'], ''),
                        (   ['13'],
                            'C1C2=c3c(=CC1)ccc1c(ccc(CC2)c31)C1=CC(=CCC1)[C]1(=CC=CC=C1)(C1=CCCC=C1)(C1=CCCC=C1)O'),
                        (['10'], '')],
                        [(['znuum'], '')]]

        csr.extract.substitute_labels(records, results)

